siteName: PremierMarkets
siteDescription: Trade CFDs with confidence. PremierMarkets offers advanced trading tools, competitive spreads, and lightning-fast execution for forex, commodities, indices, and cryptocurrencies.
brandColor: '#ED1D25'
contactEmail: contact@premiermarkets.com
supportEmail: support@premiermarkets.com
socialLinks:
  twitter: 'https://twitter.com/premiermarkets'
  linkedin: 'https://linkedin.com/company/premiermarkets'
  facebook: 'https://facebook.com/premiermarkets'
  instagram: 'https://instagram.com/premiermarkets'



